name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a test
        run: echo "CI is working!"

  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan for secrets
        run: |
          echo "Сканируем файлы на секреты..."
          if grep -r -E "(ghp_[A-Za-z0-9]{36}|AKIA[0-9A-Z]{16})" .; then
            echo "Обнаружен секрет в коде!"
            exit 1
          else
            echo " Секретов не найдено."
          fi
